version: 2

sources:
  - name: airbyte_jaffle_shop
    description: These are the tables that our extraction software manages most likely through batch jobs. 
    tables:
      - name: _airbyte_raw_orders
      - name: _airbyte_raw_customers
      - name: _airbyte_raw_payments

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']